# Generated by Django 2.2.4 on 2020-01-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DT', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.List')),
            ],
        ),
        migrations.CreateModel(
            name='ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('opt1', models.CharField(max_length=150)),
                ('opt2', models.CharField(max_length=150)),
                ('opt3', models.CharField(max_length=150)),
                ('opt4', models.CharField(max_length=150)),
                ('opt5', models.CharField(max_length=150)),
                ('opt6', models.CharField(max_length=150)),
                ('correct', models.CharField(max_length=2)),
                ('qnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.questr')),
            ],
        ),
    ]
