# Generated by Django 2.2.4 on 2020-02-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0002_ques_questr'),
    ]

    operations = [
        migrations.CreateModel(
            name='attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('DT', models.DateTimeField()),
                ('na', models.CharField(max_length=5)),
                ('correct', models.CharField(max_length=5)),
                ('wrong', models.CharField(max_length=5)),
                ('score', models.CharField(max_length=5)),
                ('qnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.questr')),
            ],
        ),
    ]
