# Generated by Django 2.2.4 on 2020-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0003_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='isradio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ques',
            name='neg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questr',
            name='qtype',
            field=models.CharField(default='h', max_length=15),
        ),
        migrations.AddField(
            model_name='questr',
            name='time',
            field=models.CharField(default='h', max_length=10),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ques',
            name='correct',
            field=models.CharField(max_length=12),
        ),
    ]
