# Generated by Django 2.2.4 on 2020-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0005_auto_20200208_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questr',
            name='time',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
