# Generated by Django 2.2.4 on 2020-03-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0006_auto_20200208_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='studlist',
            name='name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.CreateModel(
            name='resAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('rType', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('sum_click', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.List')),
            ],
        ),
    ]
