# Generated by Django 2.2.4 on 2020-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0007_auto_20200327_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='studDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('regDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
