# Generated by Django 2.2.4 on 2020-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0008_studdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaccess',
            name='course',
            field=models.CharField(max_length=200),
        ),
    ]
