# Generated by Django 2.2.4 on 2020-04-19 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0010_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ques',
            name='topic',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.CreateModel(
            name='qnr_attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('DT', models.DateTimeField()),
                ('score', models.FloatField(default=0.0)),
                ('qnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.questr')),
            ],
        ),
        migrations.CreateModel(
            name='qn_attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('stat', models.IntegerField()),
                ('qnr_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.qnr_attempt')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.ques')),
                ('quesnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.questr')),
            ],
        ),
    ]
