# Generated by Django 2.2.4 on 2020-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0011_auto_20200419_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qn_attempt',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qn_attempt',
            name='quesnr',
        ),
    ]
