from django.urls import path
from Link2 import views

urlpatterns = [
    path('', views.Link2, name='Link2'),
    path('crossofff/<list_id>', views.crossofff, name='crossofff'),
    path('courseRO/<cid>', views.courseRO, name='courseRO'),
    path('delete/<list_id>', views.delete, name='delete'),
    path('edit/<cid>', views.edit, name='edit'),
    path('addstudgetid/<list_id>', views.addstudgetid, name='addstudgetid'),
    path('addstud/<list_id>', views.addstud, name='addstud'),
    path('studlist/<sidd>', views.studlist, name='studlist'),
    path('deleteStud/<stud>/<sidd>', views.deleteStud, name='deleteStud'),
    path('courseInfo/<cid>', views.courseInfo, name='courseInfo'),
    path('updatecred/<cid>', views.updatecred, name='updatecred'),
    path('editsyll/<cid>', views.editsyll, name='editsyll'),
    path('editdesc/<cid>', views.editdesc, name='editdesc'),
    path('addTopic/<cid>', views.addTopic, name='addTopic'),
    path('delTopic/<tid>', views.delTopic, name='delTopic'),
    path('addInst/<cid>', views.addInst, name='addInst'),
    path('delInst/<instid>', views.delInst, name='delInst'),
    path('addLink/<cid>', views.addLink, name='addLink'),
    path('delLink/<linkid>', views.delLink, name='delLink'),
    path('addannc/<cid>', views.addannc, name='addannc'),
    path('delannc/<anncid>', views.delannc, name='delannc'),
    path('addassign/<cid>', views.addassign, name='addassign'),
    path('delassign/<assid>', views.delassign, name='delassign'),
    path('studR', views.studR, name='studR'),
    path('CaTdown', views.CaTdown, name='CaTdown'),
    path('RaccessT', views.RaccessT, name='RaccessT'),
    path('RaTdown', views.RaTdown, name='RaTdown'),
    path('deleteSR/<sr>', views.deleteSR, name='deleteSR'),
    path('quesr/<cid>', views.quesr, name='quesr'),
    path('qn/<pk1>/<cid>', views.qn, name='qn'),
    path('bulkqn/<pk1>/<cid>', views.bulkqn, name='bulkqn'),
    path('delquesr/<pk1>/<cid>', views.delquesr, name='delquesr'),
    path('delqn/<pk1>/<qpk>/<cid>', views.delqn, name='delqn'),
    path('quesRO/<curr_c>', views.quesRO, name='quesRO'),
    path('qnRO/<pk1>/<cr_crseid>', views.qnRO, name='qnRO'),
    path('qnr_attempts/<pk1>/<cid>', views.qnr_attempts, name='qnr_attempts'),
    path('qn_attempts/<pk1>', views.qn_attempts, name='qn_attempts'),
    path('email/<pk1>/<cid>', views.email, name='email'),
    path('Raccess/<cid>/<rtype>', views.Raccess, name='Raccess'),
]
